### ISSUE TITLE
How does this not trigger code signing errors?

### ISSUE THREAD

**Issue by alfiecg24** [Ingan121/FSUntether#3]
Good afternoon. How should you install the modified TestFlight IPA while retaining the same bundle and team ID? You cannot sign it yourself and retain the `com.apple.TestFlight` bundle ID, can you? Thanks a lot.

**Comment by Ingan121** [comment]
I'm using a paid sideloading certificate (just an Apple Distribution cert with my UDID registered). Using this cert and ESign, I can retain the `com.apple.TestFlight` bundle ID. It seems that enterprise certs are also capable of doing this. (ESign provides free enterprise certs.)
I just realized that free developer certs are not capable of doing this. I will add this info to the readme.

**Comment by alfiecg24** [comment]
Quick question - not sure if I'm missing something. How do I sign the app with the wildcard provisioning profile? Thanks.

**Comment by Ingan121** [comment]
Updated the build instructions; please try building with the new script, signing & installing the built IPA with ESign (with the enterprise cert that is prompted when you start ESign).
It seems that the integrity error is happening because of a revoked cert. The latest non-revoked cert that ESign provides is currently `XCMG Foundation Construction Machinery`, please check you're signing the IPA with that cert.

Also, would you mind if I provide an enterprise-signed FSUntether IPA online?

**Comment by alfiecg24** [comment]
I did manage to get it installed, but iproxy gives an error of `Requesting connecion to USB device handle 142 (serial: XXXXXXXX), port 1338
Error connecting to device: No such file or directory` and I cannot connect through netcat

It seems that this doesn’t work on later versions of iOS?

**Comment by Ingan121** [comment]
If you installed it using an enterprise cert, you have to install it again after trusting the cert in Settings → VPN & Device Management to get iDownload started. If iproxy still somehow doesn't work, please try using a-Shell or LibTerm on App Store to run `nc localhost 1338`.

Note that iDownload becomes dormant a few minutes after starting. You can restart it by reinstalling the IPA.

> It seems that this doesn’t work on later versions of iOS?

I even checked it working on iPadOS 17.0 Developer Beta 1 and various 16.x versions.

**Comment by alfiecg24** [comment]
Doesn’t seem to work on two different devices I’ve tried with - one with iOS 16 and one with iOS 16. Using a DCSD cable, I see the message `AMFI: constraint violation /private/var/containers/Bundle/Application/7061E83B-1B19-4518-B542-20692C001A76/TestFlight.app/Frameworks/TestFlightServices.framework/TestFlightServices has entitlements but is not a main binary`.

**Comment by alfiecg24** [comment]
Wow, it now seems to work after installing directly from your link. Must be something wrong with how I’m building it?

**Comment by alfiecg24** [comment]
Works successfully with the IPA from your direct download link on my iPhone 14 Pro running 17.0DB1 and my iPad Pro 10.5 running 16.4.1

**Comment by Ingan121** [comment]
Thanks for reporting! I hope your build also succeeds. If you have any questions, feel free to ask here.
